### ISSUE TITLE
Option to cancel and to pause the process

### ISSUE THREAD

**Issue by esimov** [sindresorhus/gifski-app#23] opened 2018-03-13 08:51 UTC
It would be great to have an option to cancel and to pause the conversion process. If i wish to cancel the current process the only option is to shut down the application. In this case the exported qif file is not getting deleted.

**Comment by sindresorhus** [comment] 2018-03-13 09:06
Duplicate of #5

**Closed by sindresorhus** 2018-03-13 09:06 UTC

**Comment by sindresorhus** [comment] 2018-03-13 09:47
@esimov The referenced issue is still open, so no, it's not yet implemented.
